config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "about",to: "about#index", as: "about"
  get "sign_up", to:"registrations#new", as: "signup"
  post "sign_up", to:"registrations#create"

  get "sign_in", to:"session#new", as:"signin"
  post "sign_in", to:"session#create"

  get "user_profile",to:"user_profile#index", as:"user_profile"
  put "update_password",to:"user_profile#update_password", as:"update_password"

  delete "logout", to:"session#destroy", as:"logout"
  
  get "password/reset", to: "password_reset#new", as:"reset_password"
  post "password/reset", to:"password_reset#create"
  get "password/reset/edit", to:"password_reset#edit"
  put "password/reset/edit", to:"password_reset#update"

  get "/auth/twitter/callback", to:"omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets

  root  to:"main#index"
end

app/models/tweet.rb
require 'oauth/request_proxy/typhoeus_request'
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: {minimum:1,maximum:200}
  validates :publish_at, presence: true
  validate :verify_publish_at?

  def verify_publish_at?
    return self.publish_at.after? 1.minutes.from_now
  end

  def published?

    self.tweet_id?
  end
  

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  def publish_to_twitter!
    options = {
	    method: :post,
      headers: {
        "User-Agent": "v2CreateTweetRuby",
        "content-type": "application/json"
      },
      body: JSON.dump({"text":body})
    }
    url = "https://api.twitter.com/2/tweets"

    consumer = OAuth::Consumer.new(
      Rails.application.credentials.dig(:twitter,:api_key),
      Rails.application.credentials.dig(:twitter,:api_secret),
      :site => 'https://api.twitter.com',
      :authorize_path => '/oauth/authenticate',
      :debug_output => false
    )

    access_token = OAuth::Token.new(
      twitter_account.token,
      twitter_account.secret
    )
    oauth_params = {:consumer => consumer, :token => access_token}

    request = Typhoeus::Request.new(url, options)
	  oauth_helper = OAuth::Client::Helper.new(request, oauth_params.merge(:request_uri => url))
	  request.options[:headers].merge!({"Authorization" => oauth_helper.header}) # Signs the request
    p request
	  response = request.run

    result = JSON.parse(response.body)

    update(tweet_id: result["data"]["id"])
    
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!, :has_any_twitter_account!
    before_action :set_tweet, only:[:edit, :update, :destroy]
    def index
        @tweets = Current.user.tweets
    end

    def new
        @tweet = Tweet.new
    end

    def create
        @tweet = Current.user.tweets.new(tweet_params)
        if @tweet.save
            redirect_to tweets_path, notice: "Tweet scheduled successfully"
        else
            render :new, alert: "Something went wrong"
        end
    end

    def edit

    end

    def update
        
        if @tweet.update(tweet_params)
            redirect_to tweets_path, notice: "Tweet edited successfully"
        else
            render :edit, alert: "Something went wrong"
        end

    end

    def destroy
        if @tweet.destroy
            redirect_to tweets_path, notice: "Tweet deleted successfully"
        else
            render :index, alert: "Unable to delete the tweet"
        end
    end
    private 
    def has_any_twitter_account!
        redirect_to root_path, alert: "No twitter account linked" if Current.user && !Current.user.twitter_accounts.any?
    end

    def tweet_params

        params.require(:tweet).permit(:twitter_account_id,:body, :publish_at)
    end

    def set_tweet
        @tweet = Current.user.tweets.find(params[:id])
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form_tweet.html.erb
<div class="d-flex flex-column justify-content-start m-4 p-2">
    <%= form_with model: tweet, method: method, data:{turbo:false} do |form|%>
        <div class="mb-3 d-flex flex-column">
            <%=form.label :twitter_account_id%>
            <%=form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {},{class:"form-control p-3"}%>
        </div>

        <div class="mb-3">
            <%= form.label :body%>
            <%= form.text_area :body, class: "form-control"%>
        </div>

        <div class="mb-3  d-flex flex-column">
            <%= form.label :publish_at%>
            <div class="d-flex flex-row m-2 child-m child-p">
                <%= form.datetime_select :publish_at, class:"p-2"%>
            </div>
        </div>

        <div class="d-flex justify-content-center align-items-center m-4">
            <%= form.button submit_text,class: "btn btn-primary  p2-2 m-2"%>
            <% if form.object.persisted?%>
                <%=button_to "Delete tweet", tweet, method: :delete,
                    class:'m-2 p-2 btn btn-danger', data:{turbo_confirm: "Are your sure?"}
                %>
            <%end%>
        </div>

        <%= render "shared/form_errors", form:form%>
    <%end%>
</div>

app/views/tweets/edit.html.erb
<div class="d-flex flex-column">
    <h1 class="d-flex justify-content-center align-items-center">Edit Form</h1>
    <%= render "form_tweet",tweet:@tweet, submit_text: "Edit Schedule", method: :put%>
      
</div>

app/views/tweets/index.html.erb
<div class="d-flex flex-column ">

    <div class="d-flex flex-row justify-content-between">
        <h1>
            Tweets
        </h1>

        <%= link_to "Create a tweet",:new_tweet, class:"btn btn-info p-3"%>
    </div>

    <div class="container-fluid flex-column justify-content-center align-items-center">
        <%@tweets.each do|tweet|%>
           
            <div class="d-flex flex-column m-4 p-3"
                style="box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px,
                rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset;
                position:relative;"
            >
                <div class="d-flex flex-wrap flex-row justify-content-between align-items-center p-2">
                    <span>
                        <h4 class="d-inline-block mr-2">Account: </h4>
                        <%=link_to  tweet.twitter_account.username,"https://twitter.com/#{tweet.twitter_account.username}",
                            class:"text-decoration-none text-dark",
                            target: :_blank
                        %>
                        
                        
                    </span>
                    <div class="d-flex flex-row mt-2">
                        <h4 class="mr-2">Created at: </h4><div class="m-1"><%=l tweet.created_at, format: :short%></div>
                    </div>
                </div>

                <div class="d-flex flex-wrap flex-row mt-2 p-2">
                    <h4>Body: </h4>
                    <div class="d-inline-block m-1">
                        <%=tweet.body %>
                    </div>
                </div>

                <div class="d-flex flex-row justify-content-between">
                    <div class='d-flex flex-row p-2 mt-2'>
                        <h4>Publish at: </h4><div class="m-1"><%=l tweet.publish_at, format: :short%></div>
                    </div>

                    <%if tweet.published?%>
                        <%=link_to "View tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}",
                            target: :_blank, class:"text-decoration-none text-info"
                        %>
                    <%else%>
                        <div class="d-flex align-items-center p-2">
                            
                            <%=link_to "Edit tweet", edit_tweet_path(tweet),class:'m-2 p-2 btn btn-outline-primary'%>
                            <%=button_to "Delete tweet", tweet, method: :delete,
                                class:'m-2 p-2 btn btn-danger', data:{turbo_confirm: "Are your sure?"}
                            %>
                        </div>
                    <%end%>
                </div>
                
            </div>
            
        <%end%>
    </div>
</div>

app/views/tweets/new.html.erb
<div class="d-flex flex-column">
    <h1>
    Schedule a Tweet
    </h1>

    <%=render "form_tweet", tweet:@tweet,method: :post,submit_text: "Create a Schedule"%>
</div>