config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "about",to: "about#index", as: "about"
  get "sign_up", to:"registrations#new", as: "signup"
  post "sign_up", to:"registrations#create"

  get "sign_in", to:"session#new", as:"signin"
  post "sign_in", to:"session#create"

  get "user_profile",to:"user_profile#index", as:"user_profile"
  put "update_password",to:"user_profile#update_password", as:"update_password"

  delete "logout", to:"session#destroy", as:"logout"
  
  get "password/reset", to: "password_reset#new", as:"reset_password"
  post "password/reset", to:"password_reset#create"
  get "password/reset/edit", to:"password_reset#edit"
  put "password/reset/edit", to:"password_reset#update"

  get "/auth/twitter/callback", to:"omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets

  root  to:"main#index"
end

app/controllers/session_controller.rb
class SessionController < ApplicationController


    def destroy

        session.delete(:user_id)
        redirect_to root_path, notice: "Successfully Logged out"
    end

    def new
    end
    
    def create
        @user = User.find_by(:email=>params[:email])

        if @user
            if @user.authenticate(params[:password])
                reset_session
                session[:user_id] = @user.id
                flash[:notice] = "You're Successfully Logged in"
                return redirect_to root_path
            end
        end
        
        flash[:alert] = "Incorrect password or email"
        render :new, status: :unprocessable_entity

    end
end

app/views/session/new.html.erb
<%= form_with url: signin_path do |form|%>
    <div class='d-flex flex-column p-2 w-100'>
        <h1 class='d-flex justify-content-center items-align-center'>Login</h1>
        <div class='p-2 m-2'>
            <%= form.label :email, role:'button' %>
            <%= form.text_field :email, class:'w-100 rounded border-light p-2', placeholder:'abc@example.com' %>
        </div>
        <div class='p-2 m-2'>
            <%= form.label :password, role:'button' %>
            <%= form.password_field :password, class:'w-100 rounded border-light p-2', placeholder:'password'%>
        </div>

        <div class='p-2 d-flex flex-column justify-content-center align-items-center m-2'>
            <%= link_to 'Forget password', :reset_password, class: 'link-info p-2'%>
            <%= form.submit "Login",class:'btn btn-primary'%>
        </div>
            
    </div>
<%end%>