config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "about",to: "about#index", as: "about"
  get "sign_up", to:"registrations#new", as: "signup"
  post "sign_up", to:"registrations#create"

  get "sign_in", to:"session#new", as:"signin"
  post "sign_in", to:"session#create"

  get "user_profile",to:"user_profile#index", as:"user_profile"
  put "update_password",to:"user_profile#update_password", as:"update_password"

  delete "logout", to:"session#destroy", as:"logout"
  
  get "password/reset", to: "password_reset#new", as:"reset_password"
  post "password/reset", to:"password_reset#create"
  get "password/reset/edit", to:"password_reset#edit"
  put "password/reset/edit", to:"password_reset#update"

  get "/auth/twitter/callback", to:"omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets

  root  to:"main#index"
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController

    def new
    end

    def create

        user = User.find_by(email:params[:email])

        if user.present?
            PasswordMailer.with(user: user).reset.deliver_now
        end

        redirect_to root_path,notice: "Email for resetting password has been sent to #{params[:email]}"
    end

    def edit 
        @user = User.find_signed!(params[:token],purpose: "password_reset")
        rescue ActiveSupport::MessageVerifier::InvalidSignature
            redirect_to signin_path, alert: "Your token has expired, please try again."
    end

    def update
        @user = User.find_signed!(params[:token],purpose:"password_reset")
        if @user.update(password_params)
            return redirect_to signin_path,notice:"Your password has been succesfully updated, Please signin"
        end
        return render :edit
    end


    private
    def password_params
        params.require(:user).permit(:password,:password_confirmation)
    end
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_reset/edit.html.erb
<div class='container border border-dark rounded p-5 h-100 shadow'>
    <h1 class='d-flex justify-content-center align-items-center'>
        Reset Password
    </h1>

    <%=form_with model:@user,url: password_reset_edit_path(token:params[:token]), method: :put, 
    class: 'd-flex flex-column justify-content-around', data:{turbo:false} do|form|%>
        <div class='p-2 m-2'>
            <%= form.label :password, role:'button' %>
            <%= form.password_field :password, class:'w-100 rounded border-light p-2', placeholder:'password'%>
        </div>
        <div class='p-2 m-2'>
            <%= form.label :password_confirmation, role:'button' %>
            <%= form.password_field :password_confirmation, class:'w-100 rounded border-light p-2', placeholder:'re-type password'%>
        </div>

        <div class='p-2 d-flex justify-content-center align-items-center m-2'>
            <%= form.submit "Reset password",class:'btn btn-primary'%>
        </div>

        <%= render "shared/form_errors", form:form%>
        
    <%end%>

</div>

app/views/password_reset/new.html.erb
<div class='container border border-dark rounded p-5 h-100 shadow'>
    <h1 class='d-flex justify-content-center align-items-center'>
        Forget Password
    </h1>

    <%=form_with url: :reset_password, method: :post, class: 'd-flex flex-column justify-content-around' do|form|%>
        <div class='p-2'>
            <%= form.label :email,role: :button, class:'p-2'%>
            <%= form.email_field :email, class:'w-100 rounded border-light p-2', placeholder:'Email'%>
        </div>

        <div class='p-2 d-flex justify-content-center align-items-center m-2'>
            <%= form.submit "Submit",class:'btn btn-primary'%>
        </div>
    <%end%>

</div>