config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "about",to: "about#index", as: "about"
  get "sign_up", to:"registrations#new", as: "signup"
  post "sign_up", to:"registrations#create"

  get "sign_in", to:"session#new", as:"signin"
  post "sign_in", to:"session#create"

  get "user_profile",to:"user_profile#index", as:"user_profile"
  put "update_password",to:"user_profile#update_password", as:"update_password"

  delete "logout", to:"session#destroy", as:"logout"
  
  get "password/reset", to: "password_reset#new", as:"reset_password"
  post "password/reset", to:"password_reset#create"
  get "password/reset/edit", to:"password_reset#edit"
  put "password/reset/edit", to:"password_reset#update"

  get "/auth/twitter/callback", to:"omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets

  root  to:"main#index"
end

app/views/shared/_flash.html.erb
<% if flash[:notice]  %>
    <div class="alert alert-info" role='alert'>
        <%= flash[:notice]%>
    </div>
<% end %>

<% if flash[:alert]  %>
<div class="alert alert-warning" role='alert'>
    <%= flash[:alert]%>
</div>
<%end%>

app/views/shared/_form_errors.html.erb
<%if form.object.errors.any? %>
    <div class='alert alert-danger'>
        <% form.object.errors.full_messages.each do|message|%>
            <div class='p-2'><%= message%></div>
        <%end%>
    </div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light p-2">
  <div class="container-fluid">
    <%= link_to "Navbar",root_path,class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home",root_path,class: "nav-link active"%>
        </li>
        <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link"%>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto">
        <% if  Current.user %>
    
          <div class='d-flex flex-row justify-content-end'>
            <% if request.original_url.split('/')[-1]!='twitter_accounts'%>
              <li class="nav-item">
                <div class='p-1 d-flex col-md justify-content-center align-items-center'>
                  <%= link_to "Twitter Account",:twitter_accounts, class:'btn btn-info'%>
                </div>
              </li>
            <%end%>
            <li class="nav-item">
              <div class='p-1 d-flex col-md justify-content-center align-items-center'>
                <%= link_to Current.user.email, :user_profile, class:'btn btn-primary'%>
              </div>
            </li>

            <li class="nav-item">
              <div class="p-1 d-flex col-md justify-content-center align-items-center">
                <%= button_to "Log Out", logout_path,method: :delete, class:'btn btn-outline-secondary'%>
              </div>
            </li>
            
          </div>
        <%else%>
          <div class='d-flex flex-row justify-content-around p-2'>
            <% if request.original_url.split('/')[-1]!='sign_in'%>
              <div class='p-2'>
                <%= link_to "Login",sign_in_path, class:'btn btn-primary'%>
              </div>
            <%end%>

            <% if request.original_url.split('/')[-1]!='sign_up'%>
              <div class='p-2'>
                <%= link_to "Sign Up",sign_up_path, class:'btn btn-outline-secondary'%>
              </div>
            <%end%>

          </div>
        <% end %>
      </ul>
    </div>
    
  </div>
</nav>